basebox = "base-centos7-1.0"

Vagrant.configure("2") do |config|
    config.vm.define "dev-ops1" do |box|
        box.vm.box = "base-ubuntu1804"
        box.ssh.private_key_path = "~/.ssh/id_ed25519"
        box.vm.hostname = 'dev-ops1'
        box.vm.network :public_network, ip: "10.0.0.10", bridge: "en1: Wi-Fi (AirPort)"
        box.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2404
            vb.cpus = 2
        end
    end

    config.vm.define "dev-controller1" do |box|
        box.vm.box = basebox
        box.ssh.private_key_path = "~/.ssh/id_ed25519"
        box.vm.hostname = 'dev-controller1'
        box.vm.network :public_network, ip: "10.0.0.150", bridge: "en1: Wi-Fi (AirPort)"
        box.disksize.size = "20GB"
        box.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2404
            vb.cpus = 2
        end
    end

    config.vm.define "dev-controller2" do |box|
        box.vm.box = basebox
        box.ssh.private_key_path = "~/.ssh/id_ed25519"
        box.vm.hostname = 'dev-controller2'
        box.vm.network :public_network, ip: "10.0.0.151", bridge: "en1: Wi-Fi (AirPort)"
        box.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2404
            vb.cpus = 2
        end
    end


    config.vm.define "dev-worker1" do |box|
        box.vm.box = basebox
        box.ssh.private_key_path = "~/.ssh/id_ed25519"
        box.vm.hostname = 'dev-worker1'
        box.vm.network :public_network, ip: "10.0.0.152", bridge: "en1: Wi-Fi (AirPort)"
        box.disksize.size = "40GB"
        box.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2404
            vb.cpus = 2
        end
    end

    config.vm.define "dev-worker2" do |box|
        box.vm.box = basebox
        box.ssh.private_key_path = "~/.ssh/id_ed25519"
        box.vm.hostname = 'dev-worker2'
        box.vm.network :public_network, ip: "10.0.0.153", bridge: "en1: Wi-Fi (AirPort)"
        box.disksize.size = "40GB"
        box.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2404
            vb.cpus = 2
        end
    end

    config.vm.define "dev-monitor1" do |box|
        box.vm.box = basebox
        box.ssh.private_key_path = "~/.ssh/id_ed25519"
        box.vm.hostname = 'dev-monitor1'
        box.vm.network :public_network, ip: "10.0.0.154", bridge: "en1: Wi-Fi (AirPort)"
        box.disksize.size = "40GB"
        box.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2404
            vb.cpus = 2
        end
    end
end
