Vagrant.configure("2") do |config|
    config.vm.define "dev-ops1" do |box|
        box.vm.box = "base-ubuntu1804"
        box.ssh.private_key_path = "~/.ssh/id_ed25519"
        box.vm.hostname = 'dev-ops1'
        box.vm.network :public_network, ip: "10.0.0.10", bridge: "en1: Wi-Fi (AirPort)"
        box.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2404
            vb.cpus = 2
        end
    end

    config.vm.define "dev-controller1" do |box|
        box.vm.box = "base-ubuntu1804"
        box.ssh.private_key_path = "~/.ssh/id_ed25519"
        box.vm.hostname = 'dev-controller1'
        box.vm.network :public_network, ip: "10.0.0.150", bridge: "en1: Wi-Fi (AirPort)"
        box.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = 2404
            vb.cpus = 2
        end
    end
end
