Vagrant.configure("2") do |config|
  config.vm.define "dev-ops1" do |box|
    box.vm.box = "base-ubuntu1804"
    box.vm.hostname = 'dev-ops1'
    box.vm.network :public_network, ip: "10.0.0.10", bridge: "en1: Wi-Fi (AirPort)"
    box.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = 2404
        vb.cpus = 2
    end
  end
end
